package crol.client.util.render.esp;

import com.mojang.blaze3d.platform.GlStateManager.DstFactor;
import com.mojang.blaze3d.platform.GlStateManager.SrcFactor;
import com.mojang.blaze3d.systems.RenderSystem;
import crol.client.CrolClient;
import crol.client.event.classes.Render3DEvent;
import crol.client.util.IUtil;
import crol.client.util.math.MathUtil;
import java.awt.Color;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.gl.ShaderProgramKeys;
import net.minecraft.client.render.BufferBuilder;
import net.minecraft.client.render.BufferRenderer;
import net.minecraft.client.render.Camera;
import net.minecraft.client.render.Tessellator;
import net.minecraft.client.render.VertexFormats;
import net.minecraft.client.render.VertexFormat.DrawMode;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.util.math.Box;
import net.minecraft.util.math.Vec3d;
import org.joml.Matrix4f;
import org.lwjgl.opengl.GL11;

@Environment(EnvType.CLIENT)
public class PlayerCube implements IUtil {
   public void render(Render3DEvent render3DEvent, PlayerEntity target) {
      MatrixStack matrices = render3DEvent.getMatrixStack();
      Camera camera = mc.gameRenderer.getCamera();
      Vec3d targetPos = target.getLerpedPos(MathUtil.getTickDelta()).subtract(camera.getPos());
      double tPosX = targetPos.x;
      double tPosY = targetPos.y;
      double tPosZ = targetPos.z;
      matrices.push();
      matrices.translate(tPosX, tPosY, tPosZ);
      RenderSystem.enableBlend();
      RenderSystem.blendFunc(SrcFactor.SRC_ALPHA, DstFactor.ONE);
      RenderSystem.disableCull();

      assert mc.player != null;

      RenderSystem.disableDepthTest();
      GL11.glEnable(2848);
      GL11.glHint(3154, 4354);
      Color themeColor = CrolClient.INSTANCE.getThemeManager().getTheme().color();
      int bloomColor = themeColor.getRGB();
      int fillColor = (new Color(themeColor.getRed(), themeColor.getGreen(), themeColor.getBlue(), 50)).getRGB();
      RenderSystem.setShader(ShaderProgramKeys.POSITION_COLOR);
      BufferBuilder buffer = Tessellator.getInstance().begin(DrawMode.TRIANGLE_STRIP, VertexFormats.POSITION_COLOR);
      Matrix4f matrix = matrices.peek().getPositionMatrix();
      buffer = Tessellator.getInstance().begin(DrawMode.DEBUG_LINE_STRIP, VertexFormats.POSITION_COLOR);
      Box box = target.getBoundingBox();
      Vec3d camPos = camera.getPos();
      double x = MathUtil.interpolate(target.getX(), target.lastRenderX, (double)mc.getRenderTickCounter().getTickDelta(false));
      double y = MathUtil.interpolate(target.getY(), target.lastRenderY, (double)mc.getRenderTickCounter().getTickDelta(false));
      double z = MathUtil.interpolate(target.getZ(), target.lastRenderZ, (double)mc.getRenderTickCounter().getTickDelta(false));
      double width = (double)2.0F;
      double minX = x - width - camPos.x;
      double minY = y - camPos.y;
      double minZ = z - width - camPos.z;
      double maxX = x + width - camPos.x;
      double maxY = y + (double)4.0F - camPos.y;
      double maxZ = z + width - camPos.z;
      buffer = Tessellator.getInstance().begin(DrawMode.QUADS, VertexFormats.POSITION_COLOR);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)minZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)maxZ).color(fillColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)minZ).color(fillColor);
      BufferRenderer.drawWithGlobalProgram(buffer.end());
      buffer = Tessellator.getInstance().begin(DrawMode.DEBUG_LINE_STRIP, VertexFormats.POSITION_COLOR);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)minZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)minY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)maxX, (float)maxY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)minY, (float)maxZ).color(bloomColor);
      buffer.vertex(matrix, (float)minX, (float)maxY, (float)maxZ).color(bloomColor);
      BufferRenderer.drawWithGlobalProgram(buffer.end());
      GL11.glDisable(2848);
      RenderSystem.enableCull();
      RenderSystem.enableDepthTest();
      RenderSystem.disableBlend();
      RenderSystem.defaultBlendFunc();
      RenderSystem.setShaderColor(1.0F, 1.0F, 1.0F, 1.0F);
      matrices.pop();
   }
}
