
package jnr.constants.platform.fake;

import jnr.constants.Constant;

public enum LastError implements Constant
{
    ERROR_INVALID_FUNCTION(1L),
    ERROR_FILE_NOT_FOUND(2L),
    ERROR_PATH_NOT_FOUND(3L),
    ERROR_TOO_MANY_OPEN_FILES(4L),
    ERROR_ACCESS_DENIED(5L),
    ERROR_INVALID_HANDLE(6L),
    ERROR_ARENA_TRASHED(7L),
    ERROR_NOT_ENOUGH_MEMORY(8L),
    ERROR_INVALID_BLOCK(9L),
    ERROR_BAD_ENVIRONMENT(10L),
    ERROR_BAD_FORMAT(11L),
    ERROR_INVALID_ACCESS(12L),
    ERROR_INVALID_DATA(13L),
    ERROR_INVALID_DRIVE(14L),
    ERROR_CURRENT_DIRECTORY(15L),
    ERROR_NOT_SAME_DEVICE(16L),
    ERROR_NO_MORE_FILES(17L),
    ERROR_WRITE_PROTECT(18L),
    ERROR_BAD_UNIT(19L),
    ERROR_NOT_READY(20L),
    ERROR_BAD_COMMAND(21L),
    ERROR_CRC(22L),
    ERROR_BAD_LENGTH(23L),
    ERROR_SEEK(24L),
    ERROR_NOT_DOS_DISK(25L),
    ERROR_SECTOR_NOT_FOUND(26L),
    ERROR_OUT_OF_PAPER(27L),
    ERROR_WRITE_FAULT(28L),
    ERROR_READ_FAULT(29L),
    ERROR_GEN_FAILURE(30L),
    ERROR_LOCK_VIOLATION(31L),
    ERROR_SHARING_VIOLATION(32L),
    ERROR_WRONG_DISK(33L),
    ERROR_SHARING_BUFFER_EXCEEDED(34L),
    ERROR_BAD_NETPATH(35L),
    ERROR_NETWORK_ACCESS_DENIED(36L),
    ERROR_BAD_NET_NAME(37L),
    ERROR_FILE_EXISTS(38L),
    ERROR_CANNOT_MAKE(39L),
    ERROR_FAIL_I24(40L),
    ERROR_INVALID_PARAMETER(41L),
    ERROR_NO_PROC_SLOTS(42L),
    ERROR_DRIVE_LOCKED(43L),
    ERROR_BROKEN_PIPE(44L),
    ERROR_DISK_FULL(45L),
    ERROR_INVALID_TARGET_HANDLE(46L),
    ERROR_WAIT_NO_CHILDREN(47L),
    ERROR_CHILD_NOT_COMPLETE(48L),
    ERROR_DIRECT_ACCESS_HANDLE(49L),
    ERROR_NEGATIVE_SEEK(50L),
    ERROR_SEEK_ON_DEVICE(51L),
    ERROR_DIR_NOT_EMPTY(52L),
    ERROR_DIRECTORY(53L),
    ERROR_NOT_LOCKED(54L),
    ERROR_BAD_PATHNAME(55L),
    ERROR_MAX_THRDS_REACHED(56L),
    ERROR_LOCK_FAILED(57L),
    ERROR_ALREADY_EXISTS(58L),
    ERROR_INVALID_STARTING_CODESEG(59L),
    ERROR_INVALID_STACKSEG(60L),
    ERROR_INVALID_MODULETYPE(61L),
    ERROR_INVALID_EXE_SIGNATURE(62L),
    ERROR_EXE_MARKED_INVALID(63L),
    ERROR_BAD_EXE_FORMAT(64L),
    ERROR_ITERATED_DATA_EXCEEDS_64k(65L),
    ERROR_INVALID_MINALLOCSIZE(66L),
    ERROR_DYNLINK_FROM_INVALID_RING(67L),
    ERROR_IOPL_NOT_ENABLED(68L),
    ERROR_INVALID_SEGDPL(69L),
    ERROR_AUTODATASEG_EXCEEDS_64k(70L),
    ERROR_RING2SEG_MUST_BE_MOVABLE(71L),
    ERROR_RELOC_CHAIN_XEEDS_SEGLIM(72L),
    ERROR_INFLOOP_IN_RELOC_CHAIN(73L),
    ERROR_FILENAME_EXCED_RANGE(74L),
    ERROR_NESTING_NOT_ALLOWED(75L),
    ERROR_PIPE_LOCAL(76L),
    ERROR_BAD_PIPE(77L),
    ERROR_PIPE_BUSY(78L),
    ERROR_NO_DATA(79L),
    ERROR_PIPE_NOT_CONNECTED(80L),
    ERROR_OPERATION_ABORTED(81L),
    ERROR_NOT_ENOUGH_QUOTA(82L),
    ERROR_MOD_NOT_FOUND(83L),
    WSAEINTR(84L),
    WSAEBADF(85L),
    WSAEACCES(86L),
    WSAEFAULT(87L),
    WSAEINVAL(88L),
    WSAEMFILE(89L),
    WSAEWOULDBLOCK(90L),
    WSAEINPROGRESS(91L),
    WSAEALREADY(92L),
    WSAENOTSOCK(93L),
    WSAEDESTADDRREQ(94L),
    WSAEMSGSIZE(95L),
    WSAEPROTOTYPE(96L),
    WSAENOPROTOOPT(97L),
    WSAEPROTONOSUPPORT(98L),
    WSAESOCKTNOSUPPORT(99L),
    WSAEOPNOTSUPP(100L),
    WSAEPFNOSUPPORT(101L),
    WSAEAFNOSUPPORT(102L),
    WSAEADDRINUSE(103L),
    WSAEADDRNOTAVAIL(104L),
    WSAENETDOWN(105L),
    WSAENETUNREACH(106L),
    WSAENETRESET(107L),
    WSAECONNABORTED(108L),
    WSAECONNRESET(109L),
    WSAENOBUFS(110L),
    WSAEISCONN(111L),
    WSAENOTCONN(112L),
    WSAESHUTDOWN(113L),
    WSAETOOMANYREFS(114L),
    WSAETIMEDOUT(115L),
    WSAECONNREFUSED(116L),
    WSAELOOP(117L),
    WSAENAMETOOLONG(118L),
    WSAEHOSTDOWN(119L),
    WSAEHOSTUNREACH(120L),
    WSAENOTEMPTY(121L),
    WSAEPROCLIM(122L),
    WSAEUSERS(123L),
    WSAEDQUOT(124L),
    WSAESTALE(125L),
    WSAEREMOTE(126L),
    WSASYSNOTREADY(127L),
    WSAVERNOTSUPPORTED(128L),
    WSANOTINITIALISED(129L),
    WSAEDISCON(130L),
    WSAENOMORE(131L),
    WSAECANCELLED(132L),
    WSAEINVALIDPROCTABLE(133L),
    WSAEINVALIDPROVIDER(134L),
    WSAEPROVIDERFAILEDINIT(135L),
    WSASYSCALLFAILURE(136L),
    WSASERVICE_NOT_FOUND(137L),
    WSATYPE_NOT_FOUND(138L),
    WSA_E_NO_MORE(139L),
    WSA_E_CANCELLED(140L),
    WSAEREFUSED(141L),
    WSAHOST_NOT_FOUND(142L),
    WSATRY_AGAIN(143L),
    WSANO_RECOVERY(144L),
    WSANO_DATA(145L);

    private final long value;
    public static final long MIN_VALUE = 1L;
    public static final long MAX_VALUE = 145L;

    private LastError(long value) {
        this.value = value;
    }

    public final int value() {
        return (int)this.value;
    }

    @Override
    public final int intValue() {
        return (int)this.value;
    }

    @Override
    public final long longValue() {
        return this.value;
    }

    @Override
    public final boolean defined() {
        return true;
    }
}

